### PR TITLE
Fix sizing modes

### PR DESCRIPTION
**Pull request by Pyreko**
It's hacky as hell but I _think_ it works now. This PR:

1. Fixes "original" sizing (which I renamed). This sizing will display the original page size, as-is.
2. Fixes fit-height and fit-width sizing to have a scrollbar.
3. Adds "fit-both" sizing.

Closes: #18.

### CODE REVIEW

**Comment by Pyreko** [comment]
If someone can test it, especially on widescreens and/or phone-sizes, that would be great.

**Comment by Hiroreco** [comment]
Not sure if it's just chrome's dev tool being weird, but everything seems to break when I'm testing out vertical monitors viewport (break as in like pages not being displayed at all in long strip). It works fine if I just use my normal viewport tho.
- Fit Both 
image
- Fit Height
image

**Comment by Pyreko** [comment]
Hmm... it looks fine for me, not sure why:

image
image

**Comment by Hiroreco** [comment]
Everything breaks now even in normal viewport for me, I'm getting this warning 
image

**Comment by Pyreko** [comment]
Hmmm... I can't replicate it but I can guess where that's coming from.

**Comment by Pyreko** [comment]
No idea if that fixes it as I can't replicate.

**Comment by Hiroreco** [comment]
Weird, guess we can ask if it's fine for the others. I'll also get the new page count thingy up in a bit

**Comment by Pyreko** [comment]
Added two possible fixes to where I suspect it might be being caused, lmk if it changes anything?

**Comment by Hiroreco** [comment]
It's still the same, the problem only occurs for fit both and original size, also got this in the console
image

- Original size
image
- Fit both
image

**Comment by Pyreko** [comment]
Uhhh... that doesn't look correct. Just as a sanity check, can you double check if you're on the latest commit? As that was an error I _did_ have but only way back.

**Comment by Hiroreco** [comment]
I think so? You added this in the latest commit right?
image
image

**Comment by Pyreko** [comment]
Hm, yeah, that's correct then. I can't reproduce what you're seeing at all though, and there's nowhere off the top of my head where I modify the width xor the height anymore...?

**Comment by Pyreko** [comment]
Can you give me the exact window size I guess?

**Comment by Hiroreco** [comment]
1536 x 729.6px

**Comment by Pyreko** [comment]
Hmmm... ah, I have another idea where an issue might be regarding loading, let me try changing that...

**Comment by Pyreko** [comment]
Just as a check - do you have caching disabled when you open the dev console?

**Comment by Hiroreco** [comment]
Yup
image

**Comment by Pyreko** [comment]
That explains it, it's doing some wonky stuff with how things are loading (for example it keeps trying to load all the dragging mp3 files each time I change pages). I can try and fix that, but if you disable it, does it still cause problems?

**Comment by Hiroreco** [comment]
Disabling the cache fixes it

**Comment by Pyreko** [comment]
Cool, and try re-enabling it with the newest commit?

**Comment by Hiroreco** [comment]
Nice, it's working fine now

**Comment by Hiroreco** [comment]
Fix for [#34](https://github.com/Matriz88/hef-website/issues/34)

**Comment by Pyreko** [comment]
image

Seems like that doesn't work for the end pages, though first page works fine now.

**Comment by Pyreko** [comment]
(resolution is a 1440 x 2560)

**Comment by Hiroreco** [comment]
Trying a different method, but before that, I don't think my part messed with anything but everytime I refresh the page I have a never ending loading icon on the screen now 
image

**Comment by Hiroreco** [comment]
> Trying a different method, but before that, I don't think my part messed with anything but everytime I refresh the page I have a never ending loading icon on the screen now image

happens for fit width, long strip,

**Comment by Pyreko** [comment]
Ugh, I know why - it's because the loading icon for other pages is not being moved correctly because it's absolute :/

**Comment by Pyreko** [comment]
K I think that fixes it, though hopefully not breaking other things in the process...

**Comment by Pyreko** [comment]
Okay I tested both fixes and I _think_ we're fine, so I'm going to merge this branch for now since it's getting long.

**Pull request merged**
