### PR TITLE
feat: some tweaks to modal sizing and tab

### PR DESCRIPTION
**Pull request by Pyreko**
Some tweaks to the modal.

image
image
image

### CODE REVIEW

**Comment by Hiroreco** [comment]
The closing icon should probably be absolute, the current one makes it look a bit wonky on smaller screens
- Current
image

- Using absolute
image

**Comment by Pyreko** [comment]
Problem with it being absolute is then it's completely broken on mobile.

image

**Comment by Pyreko** [comment]
I can make it absolute on larger screens, I guess.

**Comment by Hiroreco** [comment]
Also there's a second scrollbar for some reason (even though we have overflow-hidden on the modal box), so maybe you can look into that as well?
image

Another thing is maybe change the hovered color for the selected tab? (could make it the same accent color or sth similar)
image

**Comment by Hiroreco** [comment]
> Problem with it being absolute is then it's completely broken on mobile.
> 
> image

what if we use the close button at the bottom like before for mobile? It'd be easier to tap as well

**Comment by Pyreko** [comment]
Eh, fuck it, sure.

**Comment by Pyreko** [comment]
image

**Comment by Pyreko** [comment]
image

The tabs looks kinda weird if I use an iphone SE but eh, still usable I guess lol

**Pull request merged**
